updated psll bash script

diff --git a/psll b/psll
--- a/psll
+++ b/psll
@@ -1,5 +1,11 @@
 #!/bin/bash
 
+# Colors
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+NC='\033[0m' # No Color
+
+# Directories
 DIR=`dirname $0` # This script's directory
 PSLL_COMPILER="$DIR/psll.py"
 PYRA="$DIR/Pyramid-Scheme/pyra.rb"
@@ -8,12 +14,24 @@ PYRA="$DIR/Pyramid-Scheme/pyra.rb"
 PSLL_FILE="$PWD/${1%.*}.psll"
 PYRA_FILE="$PWD/${1%.*}.pyra"
 echo "Compiling psll to pyramid scheme"
-python $PSLL_COMPILER $PSLL_FILE -o $PYRA_FILE -f --no-compact # -v
+python $PSLL_COMPILER $PSLL_FILE -o $PYRA_FILE -f --no-compact #-v
+# python -c 'raise SyntaxError' # <- For testing
+RESULT=$?
 
-if [ "$?" -eq 0 ]; then
-    # Run pyramid scheme if compilation worked
-    echo "Running the scheme"
-    ruby $PYRA $PYRA_FILE "${@:2}"
+if [ "$RESULT" -ne 0 ]; then
+    echo -e "${RED} > Compilation failed${NC}"
+    exit $?
+else
+    echo -e "${GREEN} > Compilation successful${NC}"
 fi
+
+# Count characters in file
+wc $PSLL_FILE | awk {'print " > Psll file: " $2 " lines, " $3 " characters"'}
+wc $PYRA_FILE | awk {'print " > Pyra file: " $2 " lines, " $3 " characters"'}
+# Why, oh why is this ^ so hard to do with sed regular expressions...?
+
+# Run pyramid scheme if compilation worked
+echo "Running the scheme"
+ruby $PYRA $PYRA_FILE "${@:2}"
 
 
